### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by sefffal** [comment]
Hi @pitmonticone, I appreciate the proofread. However, I your changes (all but one) are changing the dialect from Canada/US English to UK English. Visualization is perfectly correct, and I see no reason to alter things to dialect that is not my own.

**Comment by pitmonticone** [comment]
Hi @sefffal, thanks for your review, but I believe I've just changed "viZualization" to "viSualisation".

**Comment by sefffal** [comment]
Oops, thanks for the clarification. Yes, I will gladly merge this with viZualiZation corrected to viSualiZation.

**Comment by pitmonticone** [comment]
I wrote it incorrectly in the comment. I pushed it correctly.

**Pull request merged**
